### ISSUE TITLE
Saving as sdf files

### ISSUE THREAD

**Issue by annamherz** [cole-group/FEgrow#13]
Hello! 

I've been following the tutorial for FEgrow, and at the end instead of saving the files in the pdb format I've been saving them as sdf:

`[rmol.to_file(f"{path_to_ligands}/best_conformers_{i}.sdf") for i, rmol in enumerate(rmols)]`

This part works fine, and then I edit the sdf file so it only contains the first ligand (by writing it to a new file until the END appears). I was wondering if there was a way to save only the best conformer as a file to avoid the editing step? I believe this is also partially linked to my next issue - although I am able to visualise the sdf file in PyMOL and it appears okay, when I try to load this paramaterised ligand sdf file into BioSimSpace for running FEP, it is unable to load with the following message:
`It looks like you failed to include a topology file.`

Looking at the sdf file then, it seems like part of it is missing. Looking at files that I am able to read, it seems to be that at the end of the sdf file, '$$$$ ' is missing. When I manually copy this in, it is able to be read. This is probably a result of how I get a single conformer from the file containing all of them, but even in the whole file, this '$$$$' is never present.

My overall Q is, is there a way to get a single best conformer from the rmols as an sdf file that is then able to be read?

**Comment by bieniekmateusz** [comment]
Hello. 

Each each rmol is also an RDKit molecule. In this case therefore you can do this to write each best (ie first conformer) into a single file:
```
with Chem.SDWriter('besteach.sdf') as w:
    for m in rmols:
        w.write(m)
```

Hope this helps!

**Comment by annamherz** [comment]
Great, thank you!
