### ISSUE TITLE
Issue with linker and r group selection in Jupyter tutorial

### ISSUE THREAD

**Issue by dww100** [cole-group/FEgrow#57]
I installed the current version of the repo from github using the documentation instructions but could not run through the tutorial using the Jupyter from the created conda environment. I can use the Kernel in an older Jupyter install.

This may be related to the following issue in the mols2grid dependency:
https://github.com/cbouy/mols2grid/issues/59

**Comment by bieniekmateusz** [comment]
Thanks @dww100 , could you tell us please what the `ipykernel` and `ipywidgets` versions you have?

**Comment by bieniekmateusz** [comment]
I can reproduce this when creating a new environment (`python 3.11`). I'll have a look. 

Separately, using the old environment I could not. The log: I updated to the latest `ipykernel 6.26.0`  and that worked fine with `ipywidgets 7.7.4`  as well as `ipywidgets 8.1.1` (which forced dowgrading of `mols2grid 2.00 to 0.2.4`). Trying to get back `mols2grid 2.0.0` gets me to `ipywidgets 7.8.0` with the new. All `python 3.10`.

**Comment by bieniekmateusz** [comment]
For me it turned out to be `notebook=7.0.0` - `7.0.6` versions that cause this issue, with the previous version `notebook=6.5.3` working fine. (https://github.com/cbouy/mols2grid/issues/59)

I added a version constraint to our environment.yml file. Please let me know if that's not working you.
