### ISSUE TITLE
Is it possible to grow a peptide?

### ISSUE THREAD

**Issue by amin-sagar** [cole-group/FEgrow#63]
Hello FEgrow developers. Thanks for this awesome work.
This seems like a great approach to optimize/grow small molecules.
I am wondering it it possible to start with the structure of a peptide bound to the target and grow the peptide?
Except the problem of sampling the peptide exhaustively, if there any technical issue in optimizing a peptide?

Best,
Amin.

**Comment by bieniekmateusz** [comment]
Hi Amin, there should not be any technical issues. Although I have not tired to build very large structures. The conformer generator will be as good (or relevant) as the RDKit's ETKDG algorithm (https://doi.org/10.1021/acs.jcim.5b00654) which we use under the hood. 

Please keep in mind that we're hoping to release soon new versions, one which will include parallelisation with Dask. The website will be updated once the new release is ready.

**Comment by bieniekmateusz** [comment]
It's been mentioned that one might want to evaluate whether Gnina can handle the task well. For example, if the peptides get bigger than the dataset on which gnina was trained, will it affect the accuracy of the scores?

**Comment by amin-sagar** [comment]
Thanks @bieniekmateusz 
I guess the conformation generator will create the conformation of the added/modified fragment only while most of the peptide can be restrained close to its input conformation. Is this correct?
For example, if a methyl group is added to a Tryptophan, just this methyl group and possibly the tryptophan will be optimized with ETKDG while the rest of the peptide maintains its conformation.
Am I understanding this correctly?

**Comment by bieniekmateusz** [comment]
Hi @amin-sagar, yes that is correct. In this example only the methyl group's coordinates will be sampled.
