### ISSUE TITLE
linkers + groupos

### ISSUE THREAD

**Issue by velocirraptor23** [cole-group/FEgrow#71]
Hi,

 I have made some tests, but I would like to make molecules all selcted rgroups against all selected linkers (probably all). I was wondering why it fails when I use this function .
cs.add_rgroups(linkers, [r_groups])
 r_groups has embed all r groups. Do I need one by one or can i do it programatically.

Best wishes,

Cesar

**Comment by bieniekmateusz** [comment]
I am afraid it is not an option right now. I guess a loop would be needed. I wonder if nudging the interface towards working with itertools.product, ie:
```
cs.add_rgroups( [ (linker1, rgroup1), (linker2, rgroup2), ... ])
```
which would be equivalent to:
```
cs.add_rgroups(itertools.product(all_linkers, all_rgroups))
```

**Comment by velocirraptor23** [comment]
I did this, it worked perfect:
This does a better job to make all the combinations:

You can select the groupos directly from the lists like this:

>>>r_groups = rgroups.Mol[0:50] 
>>>linker_list = linkers.Mol[6:9]

##and then:
>>>import itertools
>>>for r_group, linker in itertools.product(r_groups, linker_list):
>>>    cs.add_rgroups(linker, [r_group])

Hope this helps anyone interested.

BW,

Cesar

**Comment by bieniekmateusz** [comment]
Thanks for sharing, just to let you know, the last one will work but will not scale (because of how Dask handles it). If scalibility is ever here crucial please let us know!

**Comment by velocirraptor23** [comment]
Yes, it would really nice to have scalibility on this, because this is where it really needs to handle lots of molecules.

Thanks for your response!!

Cesar

**Comment by velocirraptor23** [comment]
By the way, I am doing this way because the graphical selection does not work properly. For some reason, it does not pick the groups. I think that way should not have a problem and make a combination of all groups selected.

**Comment by bieniekmateusz** [comment]
There is a bit of order dependance when using the graphical selection. I believe there is a function `linkers.get_selected()` which can help find out if it does select the right thing. Thanks

**Comment by bieniekmateusz** [comment]
Hey, I added this functionality and will release 2.1.0 with this feature. At the moment the code is available in the pull request if you'd like to try it. It should be merged soon into the main branch. Thanks!

**Comment by velocirraptor23** [comment]
Thanks a lot for taking the time for this. I am going to test this later today. 

Best wishes,

Cesar

**Comment by velocirraptor23** [comment]
I have tested this in a small set and it works very well. I am doing this in a bigger data set. 

Thnaks a lot.
