### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by richardjgowers** [cole-group/FEgrow#9]
Hi @bieniekmateusz currently MDAnalysis is GPL, so I'm not sure you can use it and license this as MIT.

**Comment by bieniekmateusz** [comment]
Thanks @richardjgowers for bringing this to our attention. As we have only used the `distance_array` we have not replaced it temporarily with a slower implementation and removed MDAnalysis. It is now my understanding that MDAnalysis would have to be LGPL for me to use it as a dependency, as pointed out here:
https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#LinkingOverControlledInterface
https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#GPLPlugins

Thanks, Mat

**Comment by djcole56** [comment]
Thanks again @richardjgowers. Just for future reference, we were surprised to read this as we don't distribute or modify any of the mdanalysis code. What would your recommendation be to do if we want to use mdanalysis as a dependency in future, as we do find it really useful for this sort of analysis.

**Comment by richardjgowers** [comment]
@djcole56  We are in the process of moving MDAnalysis to LGPL, so eventually you'll be able to use it as a dependency with a more permissive license.  Until then if you want to use it as a dependency you're stuck having to also license as GPL, which is both the strength and weakness of the license depending on your perspective :)

**Comment by djcole56** [comment]
Great, thanks very much for the clarification. We'll keep an eye out for the LGPL move, and check any other projects we have in that case.
